version: "1"

services:
  db:
    image: 'postgres:16'
    environment: 
        POSTGRES_DB: db
        POSTGRES_USER: developer
        POSTGRES_PASSWORD: Passw0rd33
    volumes:
      - ./db:/var/lib/postgresql/data

  web:
    volumes:
      - ./kernel:/app
    env_file:
      - ./server/.env
    build: ./server
    ports:
      - '8000:8000'
    depends_on:
      - db
