FROM python:3.12

COPY /requirements.txt /tmp/

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r /tmp/requirements.txt

COPY . /app
WORKDIR /app

COPY ./entrypoint.local.sh /entrypoint.sh
ENTRYPOINT ["bash", "/entrypoint.sh"]

