version: "1"

services:
  db:
    image: postgres
    environment: 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
        - web_nt 

  web:
    volumes:
      - ./:/app
    env_file:
      - .env
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
        - web_nt 

networks:
  web_nt:
    name: web_nt 

