name: Deploy to Server

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checkout:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: ${{ github.sha }}

  test:
    runs-on: self-hosted
    steps:

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          path: ${{ github.sha }}
          python-version: 3.12

      - name: Install dependencies
        run: |
          cd ${{ github.sha }}
          python -m pip install --upgrade pip
          pip install ruff pyright pytest

      - name: Run Ruff
        run: |
          cd ${{ github.sha }}
          ruff check .

      - name: Run Pyright
        run: | 
          cd ${{ github.sha }}
          pyright

      # - name: Run unit tests
      #   run: pytest

  deploy:
    if: github.event_name != 'pull_request'
    runs-on: self-hosted
    steps:
    - name: Environment setup
      run: |
        cd ${{ github.sha }}
        echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> server/.env
        echo DEBUG=${{ secrets.DEBUG }} >> server/.env
        echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> server/.env
        echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> server/.env
        echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> server/.env
        echo ${{ secrets.LETSENCRYPT }} >> letsencrypt

    - name: Run app 
      run: |
        cd ${{ github.sha }}
        docker stop $(docker ps -a -q) && docker system prune -af
        docker-compose up -d --build

