#!/bin/bash


show_help() {
    echo "help"
}

build_container() {

    cp /home/$USER/.pbd/pbd_configs/containres/dev-container.json $pr_name/kernel/.devcontainer/
    cp /home/$USER/.pbd/pbd_configs/containres/dev-Dockerfile $pr_name/kernel/.devcontainer/Dockerfile
    cp /home/$USER/.pbd/pbd_configs/containres/dev-docker-compose.yml $pr_name/kernel/.devcontainer/docker-compose.yml
    cp /home/$USER/.pbd/pbd_configs/containres/docker-compose.yml $pr_name/
    cp /home/$USER/.pbd/pbd_configs/containres/Dockerfile $pr_name/kernel/

    cp /home/$USER/.pbd/pbd_configs/deploy.sh $pr_name/
    cp cp /home/$USER/.pbd/pbd_configs/django_entrypoint.sh $pr_name/kernel/entrypoint.sh

}


delete_pbd() {

    read -p "Are you sure you want to delete PBD? [y/N] " answer
    if [ "$answer" = "y" ] || [ "$answer" = "Y" ]; then
        rm -rf /home/$USER/.pbd
        rm -rf /home/$USER/.local/bin/pbd
        echo "PBD deleted :("
    else
        echo "Aborted."
    fi
}


drf_template() {
    read -p "Install Django + DRF [Y/n] " agreesing
    if [ "$agreesing" = "n" ] || [ "$agreesing" = "N" ] || [ "$agreesing" = "no" ] || [ "$agreesing" = "No" ] || [ "$agreesing" = "NO" ]; then
        echo "Aborted!"
        exit 0
    fi

    read -p "Project name: " pr_name
    mkdir $pr_name

    cp -r /home/$USER/.pbd/django-template-drf $pr_name/kernel

    cat /home/$USER/.pbd/pbd_configs/django_drf_readme.md > $pr_name/README.md
    sed -i "s/projectname/$pr_name/g" $pr_name/README.md

    build_container

    xdg-open https://github.com/lyaguxafrog/python-backend-devcontainers/blob/release/docs/DJANGO_DRF.md
}


gql_template() {

    read -p "Install Django + Graphene [Y/n] " agreesing
    if [ "$agreesing" = "n" ] || [ "$agreesing" = "N" ] || [ "$agreesing" = "no" ] || [ "$agreesing" = "No" ] || [ "$agreesing" = "NO" ]; then
        echo "Aborted!"
        exit 0
    fi

    read -p "Project name: " pr_name
    mkdir $pr_name

    cp -r /home/$USER/.pbd/pbd_configs/django-gql-template $pr_name/kernel
    
    cat /home/$USER/.pbd/pbd_configs/django_gql_readme.md > $pr_name/README.md
    sed -i "s/projectname/$pr_name/g" $pr_name/README.md

    build_container

    xdg-open https://github.com/lyaguxafrog/python-backend-devcontainers/blob/release/docs/DJANGO_GRAPHENE.md

}


flask_template() {
    echo "Flask in develop!"
}



handle_arguments() {
    while getopts ":t:" opt; do
        case ${opt} in
            t)
                template=$OPTARG
                ;;
            \?)
                echo "Invalid option: -$OPTARG" 1>&2
                exit 1
                ;;
            :)
                echo "Option -$OPTARG requires an argument." 1>&2
                exit 1
                ;;
        esac
    done
    shift $((OPTIND -1))
}


choose_template() {
    if [ -z "$template" ]; then
        echo "Choose a template:"
        echo "1. Django + DRF"
        echo "2. Django + Graphene"
        echo "3. Flask"
        read -p "Enter the number of the template: " template_number
        case $template_number in
            1)
                template="drf"
                ;;
            2)
                template="gql"
                ;;
            3)
                template="flask"
                ;;
            *)
                echo "Invalid choice."
                exit 1
                ;;
        esac
    fi
}


use_template() {
    case $template in
        drf)
            drf_template
            ;;
        gql)
            gql_template
            ;;
        flask)
            flask_template
            ;;
        *)
            echo "Invalid template."
            exit 1
            ;;
    esac
}


case "$1" in
    new)
        handle_arguments "$3"

        choose_template

        use_template
        ;;
    *)
        echo "Invalid command. Use 'pbd new' or 'pbd new -t <template>'"
        exit 1
        ;;
esac
